<a href="https://colab.research.google.com/github/Purvanshhh404/Neural-Learning/blob/main/Copy_of_deep_learning_ws.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler , LabelEncoder
import pickle

In [ ]:
import pandas as pd

#Load the dataset
data= pd.read_csv("Customer Attrition.csv")
print(type(data))
data.head()

<class 'pandas.core.frame.DataFrame'>

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
#Preprocess the data
#Drop irrelevant features
print(data.columns)
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)
data.columns=data.columns.str.strip()
data.columns
data.head()
print(data.columns)

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')
Index(['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary',
       'Exited'],
      dtype='object')

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Encode categorical feature
print(data['Gender'].head(10))
label_encoder_Gender=LabelEncoder()
data['Gender']=label_encoder_Gender.fit_transform(data['Gender'])
print(data['Gender'].head(10))
data

0    Female
1    Female
2    Female
3    Female
4    Female
5      Male
6      Male
7    Female
8      Male
9      Male
Name: Gender, dtype: object
0    0
1    0
2    0
3    0
4    0
5    1
6    1
7    0
8    1
9    1
Name: Gender, dtype: int64

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
# Encoding geography feature with labelencoder will assign value
# this may consider as more priority on bigger number so will mo
from sklearn.preprocessing import OneHotEncoder
one_hot_encode_geo =OneHotEncoder()
geo_encoder= one_hot_encode_geo.fit_transform(data[['Geography']])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [ ]:
#convert Compressed sparse row sparse matrix to array
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [ ]:
one_hot_encode_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [ ]:
geo_encoded_df=pd.DataFrame(geo_encoder.toarray(),
                            columns=one_hot_encode_geo.
                            get_feature_names_out
                            (['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [ ]:
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
print(data)

      CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619       0   42       2       0.00              1          1
1             608       0   41       1   83807.86              1          0
2             502       0   42       8  159660.80              3          1
3             699       0   39       1       0.00              2          0
4             850       0   43       2  125510.82              1          1
...           ...     ...  ...     ...        ...            ...        ...
9995          771       1   39       5       0.00              2          1
9996          516       1   35      10   57369.61              1          1
9997          709       0   36       7       0.00              1          0
9998          772       1   42       3   75075.31              2          1
9999          792       0   28       4  130142.79              1          1

      IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0                  1        101348.88       1               1.0
1                  1        112542.58       0               0.0
2                  0        113931.57       1               1.0
3                  0         93826.63       0               1.0
4                  1         79084.10       0               0.0
...              ...              ...     ...               ...
9995               0         96270.64       0               1.0
9996               1        101699.77       0               1.0
9997               1         42085.58       1               1.0
9998               0         92888.52       1               0.0
9999               0         38190.78       0               1.0

      Geography_Germany  Geography_Spain
0                   0.0              0.0
1                   0.0              1.0
2                   0.0              0.0
3                   0.0              0.0
4                   0.0              1.0
...                 ...              ...
9995                0.0              0.0
9996                0.0              0.0
9997                0.0              0.0
9998                1.0              0.0
9999                0.0              0.0

[10000 rows x 13 columns]

### Merging One-Hot Encoded Geography and Dropping Original Column

We will now concatenate the `geo_encoded_df` (which contains the one-hot encoded 'Geography' features) with our main `data` DataFrame. After the concatenation, we will drop the original 'Geography' column from the `data` DataFrame as it is no longer needed.

In [ ]:
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data

KeyError: "['Geography'] not found in axis"

In [ ]:
import pickle

#save encoder
with open('label_encoder_Gender.pkl','wb') as file:
    pickle.dump(label_encoder_Gender,file)

with open('one_hot_encode_geo.pkl','wb') as file:
    pickle.dump(one_hot_encode_geo, file)

In [ ]:
#Divide the data set into independent and dependent data set
x=data.drop('Exited',axis=1)
y=data['Exited']

# Split the dataset into training and test data
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

##scale the feature
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [ ]:
x_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [ ]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [ ]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [ ]:
#for tensorflow and tensorboard to work properly

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [ ]:
x_train.shape

(8000, 12)

In [ ]:
## building model ANN- keras funcitional API
#ReLU (Rectified Linear Unit) if the input is negative
#the output is 0
#if input is positive,the output is exactly same as the input
#Dying ReLU
  model=Sequential([
    Dense(64,activation='relu',input_shape=(x_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1,activation='sigmoid')
])

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)